---
title: "Housing Price Regression"
author: "Andrew Shao"
date: "May 31, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(reshape2)
library(glmnet)
library(DAAG)
library(MASS)
```

Exploratory Data Analysis
```{r}
train <- read_csv("train.csv", col_names = TRUE)
test <- read_csv("test.csv", col_names = TRUE)
glimpse(train)

#  Storing character columns as factors
train_fac <- train[, which(summarise_all(train, is.character) == 1)] %>% 
  mutate_all(as.factor) %>%
  mutate_all(addNA) %>%
  bind_cols(train[, which(summarise_all(train, is.character) == 0)]) 
lapply(train_fac, function(x){levels(x)})
glimpse(train_fac)

#  Data set with only numeric variables (some are still categorical and need to be encoded)
train_num <- train_fac[, which(summarise_all(train_fac, is.numeric) == 1)]
train_num <- train_num[, -1]
train_num2 <- 

#  Correlation table between numeric variables
train_cor <- cor(train_num) %>%
  melt()
train_cor$value <- round(train_cor$value, 2)

#  Correlation ggplot
cor_plot <- ggplot(train_cor, aes(Var1, Var2, fill = value)) + 
  geom_tile() + 
  theme_minimal() + 
  scale_fill_gradient(low = "orange", high = "dark blue", 
                      limit = c(0, 1), space = "Lab", 
                      name="Correlation") +
  coord_fixed() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust = 1, size = 6),
        axis.text.y = element_text(size = 6),
        axis.title.y = element_blank(),
        axis.title.x = element_blank())
cor_plot

#  Numeric Variables ggplots
ggplot(train_num, aes(LotArea, log(SalePrice))) + 
  geom_point()

ggplot(train_num, aes(OverallCond, log(SalePrice))) + 
  geom_point()

ggplot(train_num, aes(GrLivArea, log(SalePrice))) + 
  geom_point()

ggplot(train_num, aes(MasVnrArea, log(SalePrice))) + 
  geom_point()

#  Correlation ggplot with only sale price
train_cor2 <- train_cor[]

#  Looking at NA values
apply(train_fac, 2, is.na) %>%
  apply(2, sum)

apply(train_num, 2, is.na) %>%
  apply(2, sum)

apply(train_fac, 1, is.na)

train_fac[which(is.na(train_fac) == 1), ]

#  Initial regressions
#  **Still figuring out what is going on with factors
glm(SalePrice ~ ., data = train_fac)

#  Regression with only numeric factors
model_num <- glm(log(SalePrice) ~ ., data = train_num)
summary(model_num)
step_num <- stepAIC(model_num, direction = "both")
plot(model_num)
predict(model_num)



```


